In [1]:
import cv2
import numpy as np

In [8]:
image = cv2.imread('./MasterOpenCV/images/input.jpg')

# Rotation with cv2.getRotationMatrix2D

In [22]:
height, width = image.shape[:2]

angle = 90
scale = 0.75

rotMatrix = cv2.getRotationMatrix2D((width/2, height/2), angle, scale)
rotated = cv2.warpAffine(image, rotMatrix, (width, height))
cv2.imshow('Rotated', rotated)
cv2.waitKey()
cv2.destroyAllWindows()

# Transposing

In [23]:
transposed = cv2.transpose(image)
cv2.imshow('Transposed', transposed)
cv2.waitKey()
cv2.destroyAllWindows()

In [29]:
rotMatrix = cv2.getRotationMatrix2D((0, 0), 30, 0.9)
print(rotMatrix)
rotMatrix2 = cv2.getRotationMatrix2D((0, 0), 30, 1)
print(rotMatrix2)

[[ 0.77942286  0.45        0.        ]
 [-0.45        0.77942286  0.        ]]
[[ 0.8660254  0.5        0.       ]
 [-0.5        0.8660254  0.       ]]




# https://en.wikipedia.org/wiki/Transformation_matrix



## A little Pet Project for deeper understanding of the underlying math

In [71]:
small_image = image[400:425,500:525]
factor = 0.2
mat = np.float32([[factor,0,0],[0,factor,0]])
new_image = cv2.warpAffine(small_image, mat, (small_image.shape[1], small_image.shape[0]))

In [72]:
print(small_image[0])
print()
print(new_image[0])

[[221 251 255]
 [137 168 191]
 [ 47  80 106]
 [ 28  57  88]
 [ 23  46  78]
 [ 30  51  83]
 [ 51  72 104]
 [135 157 192]
 [105 125 166]
 [ 49  75 112]
 [134 168 198]
 [ 96 131 157]
 [ 26  57  82]
 [ 27  57  82]
 [  4  31  58]
 [ 21  48  75]
 [ 59  88 115]
 [ 57  84 111]
 [ 28  49  76]
 [ 28  47  74]
 [ 35  57  82]
 [ 58  79 101]
 [ 15  31  54]
 [ 13  31  54]
 [ 39  60  87]]

[[221 251 255]
 [ 30  51  83]
 [134 168 198]
 [ 21  48  75]
 [ 35  57  82]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]]
